#### 2.67 异常

##### 2.67.1 异常概述

异常：就是程序出现了不正常的情况

![image-20210820113815830](C:\Users\buwan\AppData\Roaming\Typora\typora-user-images\image-20210820113815830.png)

Error: 严重问题，不需要处理
Exception: 称为异常类，它表示程序本身可以处理的问题

- RuntimeException: 在编译期是不检查的，出现问题后，需要我们回来修改代码
- 非RuntimException: 编译期就必须处理的，否则程序不能通过编译，就不能正常运行了

##### 2.67.2 JVM的默认处理方案

如果程序出现了问题，我们没有做任何处理，最终JVM会做默认的处理

- 把异常的名称，异常的原因以及异常出现的位置等信息输出在了控制台
- 程序停止执行

##### 2.67.3 异常处理值try...catch...

- 格式

  ```java
  try {
      // 可能出现异常的代码
  } catch(异常类名 变量名) {
      // 异常的处理代码
  }
  ```

执行流程：
程序会从try里面的代码开始执行
出现异常，会自动生成一个异常类对象，该异常类对象将被提交给Java运行时系统
当Java运行时系统接收到异常现象时，会到catch中去找匹配的异常类，找到后进行异常的处理
执行完毕之后，程序还可以继续往下执行

```java
public class ExceptionDemo02 {
    public static void main(String[] args) {
        System.out.println("开始");
        method();
        System.out.println("结束");
    }

    public static void method() {
        try {
            int[] arr = {1, 2, 3};
            System.out.println(arr[3]);
        } catch (ArrayIndexOutOfBoundsException e) {
            // System.out.println("你访问的数组的索引不存在");
            e.printStackTrace();
        }
    }
}
```

##### 2.67.4 Throwable的成员方法

| 方法名                        | 说明                            |
| ----------------------------- | ------------------------------- |
| public String getMessage()    | 返回此throwable的详细消息字符串 |
| public String toString()      | 返回此可抛出的简短描述          |
| public void printStackTrace() | 把异常的错误信息输出在控制台    |

```java
public class ExceptionDemo02 {
    public static void main(String[] args) {
        System.out.println("开始");
        method();
        System.out.println("结束");
    }

    public static void method() {
        try {
            int[] arr = {1, 2, 3};
            System.out.println(arr[3]);
        } catch (ArrayIndexOutOfBoundsException e) {
            // System.out.println("你访问的数组的索引不存在");
            System.out.println(e.getMessage());

            // public String toString(): 返回此可抛出的简短描述
            System.out.println(e.toString());

            // public void printStackTrace(): 把异常的错误信息输出在控制台
            e.printStackTrace();
        }
    }
}
```

##### 2.67.5 编译时异常和运行时异常的区别

Java中的异常分为两大类：编译时异常和运行时异常，也被称为受检异常和非受检异常
所有的RuntimeException类及其子类被称为运行时异常，其他的异常都是编译时异常

- 编译时异常：必须显示处理，否则可能发生错误，无法通过编译
- 运行时异常：无需显示处理，也可以和编译时异常一样处理

```java
public class ExceptionDemo03 {
    public static void main(String[] args) {
        method();
    }

    // 运行时异常
    public static void method() {
        try {
            int[] arr = {1, 2, 3};
            System.out.println(arr[3]);
        } catch (ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }
    }

    // 编译时异常
    public static void method2() {
        try {
            String s = "2048-08-09";
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse(s);
            System.out.println(d);
        }catch (ParseException e) {
            e.printStackTrace();
        }
    }
}
```

##### 2.67.6 异常处理之throws

虽然我们通过try...catch...可以对异常进行处理，但是并不是所有的情况我们都有权限进行异常的处理
也就是说，有些时候可能出现的异常时我们处理不了的，这个时候怎么办呢？

针对这种情况，Java提供了throws的处理方案。

格式：

```java
throws 异常类名;
```

注意：这个格式是跟在方法的括号后面的

- 编译时异常必须要进行处理，两种方案：try...catch...或者throws, 如果采用throws这种方案，将来谁调用谁处理
- 运行时异常可以不处理，出现问题以后，需要我们回来修改代码

##### 2.67.7 自定义异常

格式：

```java
public class 异常类名 extends Exception {
    // 无参构造
    // 带参构造
}
```

范例：

```java
public class ScoreException exntends Exception {
    public ScoreException() {
        
    }
    public ScoreException(String message) {
        super(message);
    }
}
```

##### 2.67.8 throws和throw的区别

**throws**

- 用在方法声明后面，跟的是异常类名
- 表示抛出异常，由该方法的调用者来处理
- 表示出现异常的一种可能性，并不一定发生这种异常



**throw**

- 用在方法体内，跟的是异常对象名

- 表示抛出异常，由方法体内部的语句处理

  
